### ISSUE TITLE
Authenticator is not visible in Keycloak

### ISSUE THREAD

**Issue by dawidgora** [cnieg/keycloak-login-attribute#182]
I've added jar with keycloak-login-attribute to my keycloak (/opt/keycloak/providers but also tried different locations). In my logs I see:

```
keycloak  | 2023-11-07 21:10:21,686 WARN  [org.keycloak.services] (build-17) KC-SERVICES0047: attribute-username-password-form (fr.cnieg.keycloak.providers.login.attribute.authenticator.AttributeUsernamePasswordFormFactory) is implementing the internal SPI authenticator. This SPI is internal and may change without notice
```

I don't see any other error in logs.

When I try to add new step in the duplicated browser flow, I cannot see `Attribute Username Password Form`

![CleanShot 2023-11-07 at 22 33 26@2x](https://github.com/cnieg/keycloak-login-attribute/assets/108656216/7b2c8132-a5a9-4cf3-ba49-8a5d2b2670c7)

**Comment by arnou** [comment]
Which version of keycloak are you using ?

**Comment by dawidgora** [comment]
22.0.5

**Comment by dawidgora** [comment]
I've checked your PR with the latest instructions and tried it in our project. It's working now, thank you!

![CleanShot 2023-11-09 at 12 52 06@2x](https://github.com/cnieg/keycloak-login-attribute/assets/108656216/c25e3f35-0c29-4683-88e7-265c27f54a63)
