### ISSUE TITLE
Login without login page

### ISSUE THREAD

**Issue by LDelOff** [cnieg/keycloak-login-attribute#64]
Hey!

Is it possible to use your plugin to login without using the login page.
For example, I enter into the browser line: 
`http: // address: port / auth / realms / REALMNAME / ...? Attribute = 1234`
And keycloak redirects me to a secured app
Is this a possible solution? Or it is necessary to make POST requests. If so, is it possible to exchange the attribute for an access token?
I would be glad to have any help. Thanks.

**Comment by arnou** [comment]
I don't think that's possible, no

The value of the attribute serves as an alias for the main identifier, but cannot be sufficient to authenticate the user: the credentials part will be missing

**Comment by LDelOff** [comment]
Thanks
